# Generated by Django 2.0.3 on 2018-04-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180401_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hyperventi_detail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medi_detail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chronic_dis_detail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
