# Generated by Django 2.0.3 on 2018-04-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180401_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='guardian_detail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='live_with_detail',
            field=models.CharField(default='', max_length=255),
        ),
    ]
