# Generated by Django 2.0.3 on 2018-04-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_userprofile_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheetA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa1', models.IntegerField()),
                ('qa2', models.IntegerField()),
                ('qa3', models.IntegerField()),
                ('qa4', models.IntegerField()),
                ('qa5', models.IntegerField()),
                ('qa6', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheetB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb1', models.IntegerField(verbose_name='การหกล้มอาจทำให้กระดูกหักได้')),
                ('qb2', models.IntegerField(verbose_name='ถ้าท่านหกล้มศีรษะกระแทกพื้นทำให้ได้รับบาดเจ็บรุนแรงถึงขั้นเสียชีวิตได้')),
                ('qb3', models.IntegerField(verbose_name='หากท่านไม่จัดการสิ่งกีดขวางเกะกะทางเดินอาจทำให้ท่านพิการจากการหกล้มได้')),
                ('qb4', models.IntegerField(verbose_name='หากท่านไม่จัดการสิ่งแวดล้อมภายในบ้านจะทำให้ท่านหกล้มเกิดการบาดเจ็บศีรษะกระแทกพื้นและมีโอกาสเสียชีวิตได้')),
                ('qb5', models.IntegerField(verbose_name='หากท่านไม่ปฏิบัติท่ากายบริหารเพื่อความแข็งแรงของกล้ามเนื้อจะทำให้หกล้มศีรษะกระแทกพื้นเป็นอัมพาตได้ง่าย')),
                ('qb6', models.IntegerField(verbose_name='หากท่านไม่ปฏิบัติตัวตามคำแนะนำของบุคลากรทางการแพทย์ในการป้องกันการหกล้มจะทำให้ท่านหกล้มกระดูกสะโพกหัก')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheetC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc1', models.IntegerField(verbose_name='ท่านเชื่อว่าการหกล้มเกิดจากการไม่จัดการสิ่งแวดล้อมภายในบ้าน')),
                ('qc2', models.IntegerField(verbose_name='ท่านเชื่อว่าการหกล้มเกิดจากกล้ามเนื้อไม่แข็งแรงเนื่องจากไม่ปฏิบัติท่ากายบริหาร')),
                ('qc3', models.IntegerField(verbose_name='พื้นห้องน้ำห้องส้วมที่บ้านเปียกอาจจะทำให้ท่านหกล้มได้ง่าย')),
                ('qc4', models.IntegerField(verbose_name='แสงสว่างที่บ้านไม่เพียงพอโดยเฉพาะบริเวณบันได ห้องน้ำ ทำให้เสี่ยงต่อการหกล้มได้')),
                ('qc5', models.IntegerField(verbose_name='การที่บ้านท่านไม่มีการจัดการสิ่งแวดล้อม เช่น ราวจับ ประตู ทางลาด ทำให้เสี่ยงต่อการหกล้มได้ง่าย')),
                ('qc6', models.IntegerField(verbose_name='การที่ภายในบ้านมีสิ่งกีดขวาง เกะกะทางเดิน เช่น สายไฟ ข้าวของ เครื่องใช้ทำให้เสี่ยงต่อการหกล้มได้ง่าย')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheetD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qd1', models.IntegerField()),
                ('qd2', models.IntegerField()),
                ('qd3', models.IntegerField()),
                ('qd4', models.IntegerField()),
                ('qd5', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheetE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qe1', models.IntegerField()),
                ('qe2', models.IntegerField()),
                ('qe3', models.IntegerField()),
                ('qe4', models.IntegerField()),
                ('qe5', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_set_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='answerset',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_set_id',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerSet',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionSet',
        ),
    ]
