# Generated by Django 2.0.3 on 2018-04-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180404_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gerder',
            field=models.CharField(default='', max_length=10, verbose_name='gender'),
        ),
    ]
