# Generated by Django 2.0.3 on 2018-04-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180404_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gerder',
            new_name='gender',
        ),
    ]
