# Generated by Django 2.0.3 on 2018-04-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180404_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheetc',
            name='qc1',
            field=models.PositiveSmallIntegerField(verbose_name='การปฏิบัติท่ากายบริหารทำให้กล้ามเนื้อแข็งแรงจึงไม่เกิดการหกล้มบาดเจ็บได้'),
        ),
        migrations.AlterField(
            model_name='answersheetc',
            name='qc2',
            field=models.PositiveSmallIntegerField(verbose_name='การจัดการภายในบ้านไม่ให้มีสิ่งกีดขวาง เกะกะทางเดิน เช่น สายไฟ ข้าวของ เครื่องใช้จะช่วยป้องกันการหกล้มได้'),
        ),
        migrations.AlterField(
            model_name='answersheetc',
            name='qc3',
            field=models.PositiveSmallIntegerField(verbose_name='แสงสว่างที่บ้านเพียงพอโดยเฉพาะบริเวณบันได ห้องน้ำ จะช่วยลดความเสี่ยงต่อการหกล้มได้'),
        ),
        migrations.AlterField(
            model_name='answersheetc',
            name='qc4',
            field=models.PositiveSmallIntegerField(verbose_name='การมีราวจับจะช่วยป้องกันการเสียชีวิตจากการหกล้มศีรษะกระแทกพื้นได้'),
        ),
        migrations.AlterField(
            model_name='answersheetc',
            name='qc5',
            field=models.PositiveSmallIntegerField(verbose_name='การทรงตัวได้ดีจากการทำท่ากายบริหารเป็นประจำจะช่วยป้องกันการได้รับบาดเจ็บจากการหกล้ม'),
        ),
        migrations.AlterField(
            model_name='answersheetc',
            name='qc6',
            field=models.PositiveSmallIntegerField(verbose_name='การปฏิบัติตัวตามคำแนะนำของบุคลากรทางการแพทย์สามารถป้องกันการหกล้มได้'),
        ),
        migrations.AlterField(
            model_name='answersheetd',
            name='qd1',
            field=models.PositiveSmallIntegerField(verbose_name='ท่านสามารถทำท่ากายบริหารเป็นประจำได้'),
        ),
        migrations.AlterField(
            model_name='answersheetd',
            name='qd2',
            field=models.PositiveSmallIntegerField(verbose_name='ท่านสามารถจัดการภายในบ้านไม่ให้มีสิ่งกีดขวาง เกะกะทางเดิน เช่น สายไฟ ข้าวของ เครื่องใช้ได้'),
        ),
        migrations.AlterField(
            model_name='answersheetd',
            name='qd3',
            field=models.PositiveSmallIntegerField(verbose_name='ท่านสามารถจัดการให้ที่บ้านมีแสงสว่างเพียงพอได้ โดยเฉพาะบริเวณบันได ห้องน้ำ'),
        ),
        migrations.AlterField(
            model_name='answersheetd',
            name='qd4',
            field=models.PositiveSmallIntegerField(verbose_name='ท่านสามารถปฏิบัติพฤติกรรมการป้องกันการพลัดตกหกล้มได้ตามคำแนะนำของบุคลากรทางการแพทย์'),
        ),
        migrations.AlterField(
            model_name='answersheetd',
            name='qd5',
            field=models.PositiveSmallIntegerField(verbose_name='ท่านสามารถป้องกันการหกล้มด้วยการจัดการสิ่งแวดล้อมภายในบ้าน เช่น ราวจับ ประตู ทางลาด'),
        ),
        migrations.AlterField(
            model_name='answersheete',
            name='qe1',
            field=models.PositiveSmallIntegerField(verbose_name='ท่านตั้งใจทำท่ากายบริหารเป็นประจำได้'),
        ),
        migrations.AlterField(
            model_name='answersheete',
            name='qe2',
            field=models.PositiveSmallIntegerField(verbose_name='ท่านตั้งใจจัดการภายในบ้านไม่ให้มีสิ่งกีดขวาง เกะกะทางเดิน เช่น สายไฟ ข้าวของ เครื่องใช้ได้'),
        ),
        migrations.AlterField(
            model_name='answersheete',
            name='qe3',
            field=models.PositiveSmallIntegerField(verbose_name='ท่านตั้งใจจัดการให้ที่บ้านมีแสงสว่างเพียงพอได้ โดยเฉพาะบริเวณบันได ห้องน้ำ'),
        ),
        migrations.AlterField(
            model_name='answersheete',
            name='qe4',
            field=models.PositiveSmallIntegerField(verbose_name='ท่านตั้งใจปฏิบัติพฤติกรรมการป้องกันการพลัดตกหกล้มได้ตามคำแนะนำของบุคลากรทางการแพทย์'),
        ),
        migrations.AlterField(
            model_name='answersheete',
            name='qe5',
            field=models.PositiveSmallIntegerField(verbose_name='ท่านตั้งใจป้องกันการหกล้มด้วยการจัดการสิ่งแวดล้อมภายในบ้าน เช่น ราวจับ ประตู ทางลาด'),
        ),
    ]
