# Generated by Django 2.0.3 on 2018-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180404_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age_range',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chronic_dis',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chronic_dis_detail',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chronic_dis_time',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fall_hist',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='-', max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='guardian',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='guardian_detail',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hyperventi_detail',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hyperventi_medi',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income_avg',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='live_with',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='live_with_detail',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marriage',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medi_detail',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medi_number',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
