# Generated by Django 2.0.3 on 2018-04-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180404_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.FloatField(default=0)),
                ('quest_A', models.FloatField(default=0)),
                ('quest_B', models.FloatField(default=0)),
                ('quest_C', models.FloatField(default=0)),
                ('quest_D', models.FloatField(default=0)),
                ('quest_E', models.FloatField(default=0)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='score_profile',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile'),
        ),
    ]
