# Generated by Django 2.0.3 on 2018-04-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20180406_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_sight', models.CharField(default='-', max_length=50)),
                ('balancing', models.CharField(default='-', max_length=50)),
                ('medication', models.CharField(default='-', max_length=100)),
                ('falling_in_6_months', models.CharField(default='-', max_length=50)),
                ('home', models.CharField(default='-', max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile')),
            ],
        ),
    ]
