# Generated by Django 2.0.3 on 2018-04-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
