# Generated by Django 2.0.3 on 2018-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_risk_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
